services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5433'
  nest:
    build: .
    restart: always
    env_file:
        - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
volumes:
  postgres: